// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DisAlert: typeof import('./src/components/DisAlert.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    VAlert: typeof import('vuetify/lib/components')['VAlert']
    VApp: typeof import('vuetify/lib/components')['VApp']
    VAppBar: typeof import('vuetify/lib/components')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib/components')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib/components')['VBtn']
    VDivider: typeof import('vuetify/lib/components')['VDivider']
    VExpandXTransition: typeof import('vuetify/lib/components')['VExpandXTransition']
    VIcon: typeof import('vuetify/lib/components')['VIcon']
    VList: typeof import('vuetify/lib/components')['VList']
    VListItem: typeof import('vuetify/lib/components')['VListItem']
    VListItemAction: typeof import('vuetify/lib/components')['VListItemAction']
    VListItemContent: typeof import('vuetify/lib/components')['VListItemContent']
    VListItemTitle: typeof import('vuetify/lib/components')['VListItemTitle']
    VMain: typeof import('vuetify/lib/components')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib/components')['VNavigationDrawer']
    VOverlay: typeof import('vuetify/lib/components')['VOverlay']
    VSpacer: typeof import('vuetify/lib/components')['VSpacer']
    VTextField: typeof import('vuetify/lib/components')['VTextField']
    WebNav: typeof import('./src/components/WebNav.vue')['default']
    WebsiteIcon: typeof import('./src/components/WebsiteIcon.vue')['default']
  }
}

export { }
