// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DisAlert: typeof import('./src/components/DisAlert.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    WebNav: typeof import('./src/components/WebNav.vue')['default']
    WebsiteIcon: typeof import('./src/components/WebsiteIcon.vue')['default']
  }
}

export { }
