version: 2.1
jobs:
  deploy:
    working_directory: ~/repo/webnav
    environment:
      TZ: Asia/Shanghai
    docker:
        - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '8f:11:02:f3:3e:35:37:d7:17:4d:e4:1e:6b:e8:f6:db'
      - run:
          name: Update Submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Set up Repo
          command: |
            git worktree add -B gh-pages ../public origin/gh-pages
            git config user.email "ci-build@pkuphysu.top"
            git config user.name "ci-build"
    # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Vue build
          command: |
            npm install
            npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploy to gh-pages
          command: |
            cp -r dist/* ../public
            cd ../public
            git add --all
            git commit -m "Site build at $(date '+%F %T')"
            git push
workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
