name: Test App with Cypress

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v2
      with:
        path: .yarn/cache
        key: node-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: yarn install --immutable --check-cache
